# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: int_vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='int_vector.proto',
  package='cov_Graph',
  syntax='proto3',
  serialized_pb=_b('\n\x10int_vector.proto\x12\tcov_Graph\"\"\n\nPRG_String\x12\x14\n\x08\x65lements\x18\x01 \x03(\x05\x42\x02\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRG_STRING = _descriptor.Descriptor(
  name='PRG_String',
  full_name='cov_Graph.PRG_String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='cov_Graph.PRG_String.elements', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['PRG_String'] = _PRG_STRING

PRG_String = _reflection.GeneratedProtocolMessageType('PRG_String', (_message.Message,), dict(
  DESCRIPTOR = _PRG_STRING,
  __module__ = 'int_vector_pb2'
  # @@protoc_insertion_point(class_scope:cov_Graph.PRG_String)
  ))
_sym_db.RegisterMessage(PRG_String)


_PRG_STRING.fields_by_name['elements'].has_options = True
_PRG_STRING.fields_by_name['elements']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
