name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-n-publish:
    name:    Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version:       3.8
          mamba-version:        "*"
          channels:             conda-forge,bioconda,defaults
          channel-priority:     strict
          activate-environment: make_prg
          environment-file:     environment.yaml
          auto-update-conda:    true
      - name:  Install project
        shell: bash -l {0}
        run:   |
               python -m pip install -U pip
               just install-ci
      - name: Test project
        shell: bash -l {0}
        run:  just test
      - name: Build a binary wheel and a source tarball
        shell: bash -l {0}
        run:  just build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user:     __token__
          password: ${{ secrets.PYPI_TOKEN }}